/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.FornecedorDados;
import Modelo.Fornecedor;
import com.mysql.jdbc.Util;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import Conexao.Utilizar;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
/**
 *
 * @author pc
 */
public final class JFornecedores extends javax.swing.JFrame {

    Fornecedor obj;
    FornecedorDados fornecedor = new FornecedorDados();
    
    Util util= new Util();
    private final Object[]opcao={"SIM","NÃO"};

    /**
     * Creates new form JFornecedores
     */
    public JFornecedores() {
        initComponents();
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        JBNovo = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        JBGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        JBRemover = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JBActuaizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JBPesquisar = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        setResizable(false);

        jLabel4.setText("Cidade");

        txtcidade.setName("txtcidade"); // NOI18N

        JBNovo.setText("Novo");
        JBNovo.setName("BNovo"); // NOI18N
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        txtnome.setName("txtnome"); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        txtcodigo.setEditable(false);
        txtcodigo.setName("txtcodigo"); // NOI18N

        JBGuardar.setText("Guardar");
        JBGuardar.setEnabled(false);
        JBGuardar.setName("BGuardar"); // NOI18N
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome:", "Email:", "Telefone:", "Cidade:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Telefone");

        JBRemover.setText("Remover");
        JBRemover.setEnabled(false);
        JBRemover.setName("BRemover"); // NOI18N
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        JBActuaizar.setText("Actualizar");
        JBActuaizar.setEnabled(false);
        JBActuaizar.setName("BActualizar"); // NOI18N
        JBActuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActuaizarActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");
        jLabel7.setName(""); // NOI18N

        JBPesquisar.setLabel("Pesquisar");
        JBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBPesquisarMouseClicked(evt);
            }
        });

        txtemail.setName("txtemail"); // NOI18N

        txttelefone.setName("txttelefone"); // NOI18N

        jLabel1.setText("Nome");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/apagar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        jLabel2.setText("Fornecedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JBPesquisar))
                                    .addComponent(txtemail)
                                    .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBRemover)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBActuaizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBGuardar)
                            .addComponent(JBRemover)
                            .addComponent(JBActuaizar)
                            .addComponent(JBNovo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        limparCampos();
        JBGuardar.setEnabled(true);
        JBActuaizar.setEnabled(false);
        JBRemover.setEnabled(false);
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBNovoActionPerformed

    public void tabelaUtilizador(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codfornecedor","nome","email","telefone","cidade"};
        List<Fornecedor> lista = fornecedor.mostrar();
        
        for(Fornecedor c:lista){
            dados.add(new Object[]{c.getCodfornecedor(),c.getNomeforn(),c.getEmailforn(),c.getTelefoneforn(),c.getCidadeforn()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    public void tabelaFornecedor(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codfornecedor","nome","email","telefone","cidade"};
        List<Fornecedor> lista = fornecedor.pesquisar(obj);
        
        for(Fornecedor c:lista){
            dados.add(new Object[]{c.getCodfornecedor(),c.getNomeforn(),c.getEmailforn(),c.getTelefoneforn(),c.getCidadeforn()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    FornecedorDados DAO = new FornecedorDados();
                    if(DAO.incluirFornecedor(obj)){
                        JOptionPane.showMessageDialog(this,"Registo Salvo com sucesso!");
                        limparCampos();
                        JBGuardar.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(this,"Nao foi possivel salvar no banco!");
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txtcodigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
        txtnome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim());
        txtemail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim());
        txttelefone.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().trim());
        txtcidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString().trim());
        JBActuaizar.setEnabled(true);
        JBRemover.setEnabled(true);
        JBGuardar.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
        int escolha = JOptionPane.showOptionDialog(null, " DESEJA APAGAR OS DADOS ?", "ESCOLHER OPÇÃO", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]);

        if (escolha == 0) {
            if(validarCampos()){
                obj = new Fornecedor();
                obj.setCodfornecedor(parseInt(txtcodigo.getText()));
                fornecedor.Remover(obj);
                try {
                    tabelaUtilizador(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                }
                limparCampos();
                JBGuardar.setEnabled(false);
                JBActuaizar.setEnabled(false);
                JBRemover.setEnabled(false);
            }
        }
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void JBActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActuaizarActionPerformed
        if(validarCampos()){
            obj = new Fornecedor();
            obj.setCodfornecedor(parseInt(txtcodigo.getText()));
            obj.setNomeforn(txtnome.getText());
            obj.setEmailforn(txtemail.getText());
            obj.setCidadeforn(txtcidade.getText());
            obj.setTelefoneforn(parseInt(txttelefone.getText()));
            fornecedor.Actualizar(obj);
            try {
                tabelaUtilizador(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBActuaizarActionPerformed

    private void JBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBPesquisarMouseClicked
        // TODO add your handling code here:
        obj = new Fornecedor();
        obj.setNomeforn(txtnome.getText());
        try {
            tabelaFornecedor(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBPesquisarMouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        obj = new Fornecedor();
        obj.setNomeforn(txtnome.getText());
        try {
            tabelaFornecedor(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFornecedores().setVisible(true);
            }
        });
    }
    
     private boolean validarCampos(){
          if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtnome.requestFocus();
            return false;
            }
          if(txtcidade.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtcidade.requestFocus();
            return false;
            }
        return true;
    }
    private boolean preencherObjecto(){
        obj = new Fornecedor();
        obj.setNomeforn(txtnome.getText());
        obj.setEmailforn(txtemail.getText());
        obj.setCidadeforn(txtcidade.getText());
        obj.setTelefoneforn(parseInt(txttelefone.getText()));
        return true;
    }
    private void limparCampos(){
        txtcodigo.setText("");
        txtnome.setText("");
        txtemail.setText("");
        txtcidade.setText("");
        txttelefone.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBActuaizar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
