/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.FuncionarioDados;
import Modelo.Funcionario;
import com.mysql.jdbc.Util;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import Conexao.Utilizar;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
/**
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pc
 */
public final class JFuncionarios extends javax.swing.JFrame {

    Funcionario obj;
    FuncionarioDados funcionario = new FuncionarioDados();
    
    Util util= new Util();
    private final Object[]opcao={"SIM","NÃO"};
    /**
     * Creates new form JFuncionarios
     */
    public JFuncionarios() {
        initComponents();
         try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     public void tabelaUtilizador(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codfuncionario","nome","bi","email","telefone","senha", "codtipo"};
        List<Funcionario> lista = funcionario.mostrar();
        
        for(Funcionario c:lista){
            dados.add(new Object[]{c.getCodfunc(),c.getNomefunc(),c.getBifunc(),c.getEmailfunc(),c.getTelefonefunc(),c.getSenhafunc(), c.getCodtipo()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    
    public void tabelaPesquisar(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codfuncionario","nome","bi","email","telefone","senha", "codtipo"};
        List<Funcionario> lista = funcionario.pesquisar(obj);
        
        for(Funcionario c:lista){
            dados.add(new Object[]{c.getCodfunc(),c.getNomefunc(),c.getBifunc(),c.getEmailfunc(),c.getTelefonefunc(),c.getSenhafunc(), c.getCodtipo()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBNovo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        JBPesquisar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        JBGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JBRemover = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBActuaizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtbi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        cmbcodtipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        jLabel1.setText("Funcionarios");

        JBNovo.setText("Novo");
        JBNovo.setName("BNovo"); // NOI18N
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");
        jLabel7.setName(""); // NOI18N

        txtnome.setName("txtnome"); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        JBPesquisar.setLabel("Pesquisar");
        JBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBPesquisarMouseClicked(evt);
            }
        });

        txtcodigo.setEditable(false);
        txtcodigo.setName("txtcodigo"); // NOI18N

        txttelefone.setName("txttelefone"); // NOI18N

        JBGuardar.setText("Guardar");
        JBGuardar.setEnabled(false);
        JBGuardar.setName("BGuardar"); // NOI18N
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel6.setText("Telefone:");

        JBRemover.setText("Remover");
        JBRemover.setEnabled(false);
        JBRemover.setName("BRemover"); // NOI18N
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });

        jLabel4.setText("Função:");

        jLabel5.setText("Senha:");

        JBActuaizar.setText("Actualizar");
        JBActuaizar.setEnabled(false);
        JBActuaizar.setName("BActualizar"); // NOI18N
        JBActuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActuaizarActionPerformed(evt);
            }
        });

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome:", "Bi:", "Email:", "Telefone:", "Senha:", "CodTipo:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtbi.setName("txttelefone"); // NOI18N

        jLabel8.setText("BI:");

        jLabel9.setText("Email:");

        txtemail.setName("txtemail"); // NOI18N

        cmbcodtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Caixa", "Administrador", "Gerente" }));
        cmbcodtipo.setToolTipText("");
        cmbcodtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcodtipoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/apagar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        txtsenha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txtsenha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtsenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBActuaizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtemail)
                                            .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                                .addGap(12, 12, 12)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JBPesquisar))
                                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtnome)
                                            .addComponent(cmbcodtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbcodtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBActuaizar)
                            .addComponent(JBRemover)
                            .addComponent(JBGuardar)
                            .addComponent(JBNovo))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        limparCampos();
        JBGuardar.setEnabled(true);
        JBActuaizar.setEnabled(false);
        JBRemover.setEnabled(false);
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBNovoActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
       if (cmbcodtipo.getSelectedIndex() == 0 )
       {
         JOptionPane.showMessageDialog(this,"Selecione a Função!");  
       }
       else{
        try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    FuncionarioDados DAO = new FuncionarioDados();
                    if(DAO.incluirFuncionario(obj)){
                        JOptionPane.showMessageDialog(this,"Registo Salvo com sucesso!");
                        limparCampos();
                        JBGuardar.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(this,"Nao foi possivel salvar no banco!");
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
        int escolha = JOptionPane.showOptionDialog(null, " DESEJA APAGAR OS DADOS ?", "ESCOLHER OPÇÃO", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]);

        if (escolha == 0) {
            if(validarCampos()){
                obj = new Funcionario();
                obj.setCodfunc(parseInt(txtcodigo.getText()));
                funcionario.Remover(obj);
                try {
                    tabelaUtilizador(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(JFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                limparCampos();
                JBGuardar.setEnabled(false);
                JBActuaizar.setEnabled(false);
                JBRemover.setEnabled(false);
            }
        }
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void JBActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActuaizarActionPerformed
        if (cmbcodtipo.getSelectedIndex() == 0 )
       {
         JOptionPane.showMessageDialog(this,"Selecione a Função!");  
       }
        else{
        if(validarCampos()){
            obj = new Funcionario();
            obj.setCodfunc(parseInt(txtcodigo.getText()));
            obj.setNomefunc(txtnome.getText());
            obj.setBifunc(txtbi.getText());
            obj.setEmailfunc(txtemail.getText());
            obj.setTelefonefunc(parseInt(txttelefone.getText()));
            obj.setSenhafunc(txtsenha.getText());
            obj.setCodtipo(cmbcodtipo.getSelectedIndex());
            funcionario.Actualizar(obj);
            try {
                tabelaUtilizador(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_JBActuaizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txtcodigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
        txtnome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim());
        txtbi.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim());
        txtemail.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().trim());
        txttelefone.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString().trim());
        txtsenha.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString().trim());
        cmbcodtipo.setSelectedIndex(parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString().trim()));
        JBActuaizar.setEnabled(true);
        JBRemover.setEnabled(true);
        JBGuardar.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbcodtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcodtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcodtipoActionPerformed

    private void JBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBPesquisarMouseClicked
        // TODO add your handling code here:
        obj = new Funcionario();
        obj.setNomefunc(txtnome.getText());
        try {
            tabelaPesquisar(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBPesquisarMouseClicked

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        obj = new Funcionario();
        obj.setNomefunc(txtnome.getText());
        try {
            tabelaPesquisar(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_formWindowClosed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed

    }//GEN-LAST:event_txtsenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFuncionarios().setVisible(true);
            }
        });
    }
    
     private boolean validarCampos(){
          if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtnome.requestFocus();
            return false;
            }
          if(txtsenha.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite a senha!");
            txtsenha.requestFocus();
            return false;
            }
        return true;
    }
    private boolean preencherObjecto(){
        obj = new Funcionario();
        obj.setNomefunc(txtnome.getText());
        obj.setBifunc(txtbi.getText());
        obj.setEmailfunc(txtemail.getText());
        obj.setTelefonefunc(parseInt(txttelefone.getText()));
        obj.setSenhafunc(txtsenha.getText());
        obj.setCodtipo(cmbcodtipo.getSelectedIndex());
        
        return true;
    }
    private void limparCampos(){
        txtcodigo.setText("");
        txtnome.setText("");
        txtbi.setText("");
        txtemail.setText("");
        txtsenha.setText("");
        txttelefone.setText("");
        cmbcodtipo.getSelectedIndex();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBActuaizar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JComboBox<String> cmbcodtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbi;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttelefone;
    // End of variables declaration//GEN-END:variables
}
