/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.ProdutoDados;
import Modelo.Produto;
import com.mysql.jdbc.Util;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import Conexao.Utilizar;
import static java.lang.Integer.parseInt;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author pc
 */
public final class JProdutos extends javax.swing.JFrame {

    Produto obj;
    ProdutoDados produto = new ProdutoDados();
    String nome;
    Util util= new Util();
    private final Object[]opcao={"SIM","NÃO"};
    /**
     * Creates new form JProdutos
     */
    public JProdutos() {
        initComponents();
        inicializarData();
        try {
                tabelaUtilizador(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdata = new javax.swing.JTextField();
        JBActuaizar = new javax.swing.JButton();
        JBNovo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        JBPesquisar = new javax.swing.JButton();
        txtstock = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtprecounit = new javax.swing.JTextField();
        JBGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JBRemover = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcodfornecedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(855, 390));
        setResizable(false);
        setSize(new java.awt.Dimension(855, 390));

        txtdata.setEditable(false);
        txtdata.setName("txtdata"); // NOI18N

        JBActuaizar.setText("Actualizar");
        JBActuaizar.setEnabled(false);
        JBActuaizar.setName("BActualizar"); // NOI18N
        JBActuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActuaizarActionPerformed(evt);
            }
        });

        JBNovo.setText("Novo");
        JBNovo.setName("BNovo"); // NOI18N
        JBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNovoActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");
        jLabel7.setName(""); // NOI18N

        txtnome.setName("txtnome"); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        JBPesquisar.setLabel("Pesquisar");
        JBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBPesquisarMouseClicked(evt);
            }
        });
        JBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPesquisarActionPerformed(evt);
            }
        });

        txtstock.setName("txtstock"); // NOI18N

        txtcodigo.setEditable(false);
        txtcodigo.setName("txtcodigo"); // NOI18N

        txtprecounit.setName("txtprecounit"); // NOI18N

        JBGuardar.setText("Guardar");
        JBGuardar.setEnabled(false);
        JBGuardar.setName("BGuardar"); // NOI18N
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição");

        jLabel6.setText("Preço Unitário");

        JBRemover.setText("Remover");
        JBRemover.setEnabled(false);
        JBRemover.setName("BRemover"); // NOI18N
        JBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRemoverActionPerformed(evt);
            }
        });

        jLabel4.setText("Data");

        jLabel5.setText("Stock");

        txtcodfornecedor.setName("txtcidade"); // NOI18N

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descricao:", "Precounitl:", "Stock:", "Data:", "CodFornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setText("CodFornecedor");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/apagar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 2, 18)); // NOI18N
        jLabel2.setText("Produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBRemover)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBActuaizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtprecounit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(163, 163, 163)
                        .addComponent(JBPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtprecounit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtcodfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBGuardar)
                            .addComponent(JBRemover)
                            .addComponent(JBActuaizar)
                            .addComponent(JBNovo)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActuaizarActionPerformed
        if(validarCampos()){
            obj = new Produto();
            obj.setCodproduto(parseInt(txtcodigo.getText()));
            obj.setDescricaoproduto(txtnome.getText());
            obj.setStock(parseInt(txtstock.getText()));
            obj.setData(txtdata.getText());
            obj.setPrecounit(parseInt(txtprecounit.getText()));
            obj.setCodfornecedor(parseInt(txtcodfornecedor.getText()));
            produto.Actualizar(obj);
            try {
                tabelaUtilizador(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBActuaizarActionPerformed

    private void JBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNovoActionPerformed
        limparCampos();
        JBGuardar.setEnabled(true);
        JBActuaizar.setEnabled(false);
        JBRemover.setEnabled(false);
        inicializarData();
    }//GEN-LAST:event_JBNovoActionPerformed

    public void tabelaUtilizador(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codproduto","descricao","precounit","stock","data","codfornecedor"};
        List<Produto> lista = produto.mostrar();
        
        for(Produto c:lista){
            dados.add(new Object[]{c.getCodproduto(),c.getDescricaoproduto(),c.getPrecounit(),c.getStock(),c.getData(),c.getCodfornecedor()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    public void tabelaPesquisar(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codproduto","descricao","precounit","stock","data","codfornecedor"};
        List<Produto> lista = produto.pesquisar(obj);
        
        for(Produto c:lista){
            dados.add(new Object[]{c.getCodproduto(),c.getDescricaoproduto(),c.getPrecounit(),c.getStock(),c.getData(),c.getCodfornecedor()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    ProdutoDados DAO = new ProdutoDados();
                    if(DAO.incluirProduto(obj)){
                        JOptionPane.showMessageDialog(this,"Registo Salvo com sucesso!");
                        limparCampos();
                        JBGuardar.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(this,"Nao foi possivel salvar no banco!");
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        try {
            tabelaUtilizador(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txtcodigo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
        txtnome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim());
        txtprecounit.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim());
        txtstock.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().trim());
        txtdata.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString().trim());
        txtcodfornecedor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString().trim());
        JBActuaizar.setEnabled(true);
        JBRemover.setEnabled(true);
        JBGuardar.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void JBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRemoverActionPerformed
        int escolha = JOptionPane.showOptionDialog(null, " DESEJA APAGAR OS DADOS ?", "ESCOLHER OPÇÃO", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]);

        if (escolha == 0) {
            if(validarCampos()){
                obj = new Produto();
                obj.setCodproduto(parseInt(txtcodigo.getText()));
                produto.Remover(obj);
                try {
                    tabelaUtilizador(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(JProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
                limparCampos();
                inicializarData();
                JBGuardar.setEnabled(false);
                JBRemover.setEnabled(false);
                JBActuaizar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_JBRemoverActionPerformed

    private void JBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBPesquisarMouseClicked
        // TODO add your handling code here:
        obj = new Produto();
        obj.setDescricaoproduto(txtnome.getText());
        try {
                    tabelaPesquisar(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(JProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_JBPesquisarMouseClicked

    private void JBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPesquisarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBPesquisarActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        obj = new Produto();
        obj.setDescricaoproduto(txtnome.getText());
        try {
                    tabelaPesquisar(jTable1);
                } catch (SQLException ex) {
                    Logger.getLogger(JProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JProdutos().setVisible(true);
            }
        });
        
    }
    
    private void inicializarData(){
         String formatodata = null; 
         Date data = new Date();
         DateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
         formatodata = formato.format(data);
         txtdata.setText(formatodata);
    }
    
     private boolean validarCampos(){
          if(txtnome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtnome.requestFocus();
            return false;
            }
          if(txtprecounit.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtprecounit.requestFocus();
            return false;
            }
        return true;
    }
    private boolean preencherObjecto(){
        obj = new Produto();
        obj.setDescricaoproduto(txtnome.getText());
        obj.setStock(parseInt(txtstock.getText()));
        obj.setData(txtdata.getText());
        obj.setPrecounit(parseInt(txtprecounit.getText()));
        obj.setCodfornecedor(parseInt(txtcodfornecedor.getText()));
        return true;
    }
    private void limparCampos(){
        txtcodigo.setText("");
        txtnome.setText("");
        txtprecounit.setText("");
        txtstock.setText("");
        txtdata.setText("");
        txtcodfornecedor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBActuaizar;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBNovo;
    private javax.swing.JButton JBPesquisar;
    private javax.swing.JButton JBRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcodfornecedor;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtprecounit;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

}
