/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.DetalheDados;
import Conexao.ProdutoDados;
import Modelo.Produto;
import com.mysql.jdbc.Util;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import Conexao.Utilizar;
import Conexao.VendaDados;
import Modelo.DetalheVenda;
import Modelo.Venda;
import static Visao.JPrincipal.codigo_usuario;
import static java.lang.Integer.parseInt;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;


/**
 *
 * @author pc
 */
public class JVenda extends javax.swing.JFrame {
    int confirm = 1;
    Produto obj;
    DetalheVenda obj2;
    Venda obj3;
    ProdutoDados produto = new ProdutoDados();
    DetalheDados DetalheVenda = new DetalheDados();
    VendaDados venda = new VendaDados();
    Util util= new Util();
    private final Object[]opcao={"SIM","NÃO"};
    int prec;
    int quant;
    public static Integer codigo_usuario;
    /**
     * Creates new form JProdutos
     */
    public JVenda() {
        initComponents();
        inicializarbotao();
        inicializarData();
        btfinalizar.setEnabled(false);
        txtcodfunc.setVisible(false);
        jLabel16.setVisible(false);
        try {
                tabelaproduto(jTable2);
            } catch (SQLException ex) {
                Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
            }
        codigo_usuario = JLogin.codigo_usuario;
        txtcodfunc.setText(Integer.toString(codigo_usuario));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtquantidade = new javax.swing.JTextField();
        txtpreco = new javax.swing.JTextField();
        btinserir = new javax.swing.JButton();
        btnovo = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btcancelar = new javax.swing.JButton();
        btnovofactura = new javax.swing.JButton();
        btfinalizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btactualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtcodproduto = new javax.swing.JTextField();
        txtvenda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtrecebido = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttroco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcodfunc = new javax.swing.JTextField();
        bttroco = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        setLocation(new java.awt.Point(250, 80));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(940, 610));
        setResizable(false);
        setSize(new java.awt.Dimension(940, 610));

        jLabel1.setText("Produto:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Preço:");

        txtnome.setName("txtnome"); // NOI18N
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        txtquantidade.setName("txtquantidade"); // NOI18N

        txtpreco.setEditable(false);
        txtpreco.setName("txtpreco"); // NOI18N
        txtpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoActionPerformed(evt);
            }
        });

        btinserir.setText("Inserir");
        btinserir.setName("btinserir"); // NOI18N
        btinserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btinserirMouseClicked(evt);
            }
        });
        btinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinserirActionPerformed(evt);
            }
        });

        btnovo.setText("Apagar");
        btnovo.setName("btnovo"); // NOI18N
        btnovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnovoMouseClicked(evt);
            }
        });

        bteliminar.setText("Eliminar");
        bteliminar.setName("bteliminar"); // NOI18N
        bteliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bteliminarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel5.setText("Formulário de Vendas");

        jLabel6.setText("Factura:");

        jScrollPane1.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código:", "Produto:", "Preço:", "Quantidade:", "Total:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btcancelar.setText("Cancelar");
        btcancelar.setName("btcancelar"); // NOI18N
        btcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcancelarMouseClicked(evt);
            }
        });

        btnovofactura.setText("Novo");
        btnovofactura.setName("btnovovenda"); // NOI18N
        btnovofactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnovofacturaMouseClicked(evt);
            }
        });
        btnovofactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovofacturaActionPerformed(evt);
            }
        });

        btfinalizar.setText("Finalizar");
        btfinalizar.setName("btfinalizar"); // NOI18N
        btfinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btfinalizarMouseClicked(evt);
            }
        });
        btfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfinalizarActionPerformed(evt);
            }
        });

        jLabel7.setText("Total:");

        txttotal.setEditable(false);
        txttotal.setText("0");
        txttotal.setName("txttotal"); // NOI18N

        jLabel8.setText("aKZ");

        jLabel9.setText("aKZ");

        btactualizar.setText("Actualizar");
        btactualizar.setName("btactualizar"); // NOI18N
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });

        jScrollPane2.setToolTipText("");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descricao:", "Precounitl:", "Stock:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName(""); // NOI18N
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel10.setText("Cod produto:");
        jLabel10.setName("txtcodproduto"); // NOI18N

        txtcodproduto.setEditable(false);
        txtcodproduto.setName("txtcodproduto"); // NOI18N
        txtcodproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodprodutoActionPerformed(evt);
            }
        });

        txtvenda.setEditable(false);
        txtvenda.setName("txtfactura"); // NOI18N

        jLabel11.setText("Recebido:");
        jLabel11.setName("txtnome"); // NOI18N

        txtrecebido.setText("0");
        txtrecebido.setName("txtrecebido"); // NOI18N
        txtrecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecebidoActionPerformed(evt);
            }
        });
        txtrecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrecebidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrecebidoKeyTyped(evt);
            }
        });

        txtdata.setEditable(false);

        jLabel2.setText("Data:");

        jLabel12.setText("Nome cliente:");
        jLabel12.setName("txtnome"); // NOI18N

        txtcliente.setName("txtcliente"); // NOI18N

        jLabel13.setText("Troco:");

        txttroco.setEditable(false);
        txttroco.setName("txttotal"); // NOI18N

        jLabel14.setText("aKZ");

        jLabel15.setText("aKZ");

        jLabel16.setText("Cod Func.:");

        txtcodfunc.setEditable(false);

        bttroco.setText("Troco");
        bttroco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttrocoMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/apagar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 340, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(29, 29, 29)
                        .add(txtnome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(layout.createSequentialGroup()
                            .add(btactualizar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(btnovo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(bteliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(btinserir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel3)
                        .add(jLabel4))
                    .add(layout.createSequentialGroup()
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtquantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txtpreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(txtcodproduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel8)))))
                .add(53, 53, 53)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtvenda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(btcancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnovofactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btfinalizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 131, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(3, 3, 3)
                                .add(jLabel12)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(txttroco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel14))
                                    .add(txtcliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(layout.createSequentialGroup()
                                        .add(3, 3, 3)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel13)
                                            .add(jLabel11))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(txttotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel9))
                                    .add(layout.createSequentialGroup()
                                        .add(txtrecebido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel15)))
                                .add(26, 26, 26)))
                        .add(bttroco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(253, 253, 253)
                        .add(jLabel5))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(608, 608, 608)
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtcodfunc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46)
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtdata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 48, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jButton1)))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtdata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(txtcodfunc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(txtnome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(txtcodproduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(txtquantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(txtpreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnovo)
                            .add(bteliminar)
                            .add(btactualizar))
                        .add(9, 9, 9)
                        .add(btinserir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(txtvenda, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(txttotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(txtrecebido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel15)
                            .add(bttroco))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel13)
                            .add(txttroco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel14))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(txtcliente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnovofactura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btcancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btfinalizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(62, 62, 62))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btinserirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txtcodproduto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString().trim());
        txtnome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString().trim());
        txtpreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().trim());
        txtquantidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().trim());
        btactualizar.setEnabled(true);
        btnovo.setEnabled(true);
        bteliminar.setEnabled(true);
        prec = parseInt(txtpreco.getText()); 
        quant = parseInt(txtquantidade.getText()); 
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnovofacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovofacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnovofacturaActionPerformed
    public void tabelaproduto(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codproduto","descricao","precounit","stock"};
        List<Produto> lista = produto.mostrar();
        
        for(Produto c:lista){
            dados.add(new Object[]{c.getCodproduto(),c.getDescricaoproduto(),c.getPrecounit(),c.getStock()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    public void tabelapesquisar(JTable tabela) throws SQLException{
        ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"codproduto","descricao","precounit","stock"};
        List<Produto> lista = produto.pesquisar(obj);
        
        for(Produto c:lista){
            dados.add(new Object[]{c.getCodproduto(),c.getDescricaoproduto(),c.getPrecounit(),c.getStock()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    public void tabelafactura(JTable tabela) throws SQLException{
         ArrayList dados=new ArrayList();
         String[] colunas=new String[]{"Codproduto","Produto","preço","Quantidade","total"};
        List<Venda> lista = venda.mostrar(obj3);
        
        for(Venda c:lista){
            dados.add(new Object[]{c.getCproduto(),c.getDescproduto(),c.getTotal(),c.getQuant(),c.getPreco()});
        }
       
        Utilizar modelo = new Utilizar(dados, colunas);
        
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabela.getTableHeader().setReorderingAllowed(false); 
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    } 
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        txtcodproduto.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString().trim());
        txtnome.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString().trim());
        txtpreco.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString().trim());
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoActionPerformed

    private void txtcodprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodprodutoActionPerformed
    private boolean preencherObjecto(){
        obj2 = new DetalheVenda();
        obj2.setCodproduto(parseInt(txtcodproduto.getText()));
        obj2.setQuantidade(parseInt(txtquantidade.getText()));
        obj2.setPreco(parseInt(txtpreco.getText()));
        obj2.setCodvenda(parseInt(txtvenda.getText()));
        return true;
    }
    
    private boolean preencherObjecto2(){
        obj3 = new Venda();
        obj3.setCodvenda(parseInt(txtvenda.getText()));
        obj3.setNomecliente(txtcliente.getText());
        obj3.setDatavenda(txtdata.getText());
        obj3.setPrecototal(parseInt(txttotal.getText()));
        obj3.setCodfunc(parseInt(txtcodfunc.getText()));
        return true;
    }
     private boolean validarCampos(){
          if(txtcodproduto.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtcodproduto.requestFocus();
            return false;
            }
          if(txtpreco.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtpreco.requestFocus();
            return false;
            }
          if(txtvenda.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtvenda.requestFocus();
            return false;
          }
            if(txtquantidade.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome!");
            txtquantidade.requestFocus();
            return false;
           }
        return true;
    }
     
    private boolean validarCampos2(){
          if(txtcliente.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o nome do cliente!");
            txtcliente.requestFocus();
            return false;
            }
          if(txttotal.getText().equals("")){
            JOptionPane.showMessageDialog(this,"A factura esta vazia!");
            txttotal.requestFocus();
            return false;
          }
            if(txtrecebido.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o valor de recebido!");
            txtrecebido.requestFocus();
            return false;
           }
            if(txtcodfunc.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Digite o codigo de funcionario!");
            txtcodfunc.requestFocus();
            return false;
           }
        return true;
    }
     private void limparCampos(){
        txtcodproduto.setText("");
        txtpreco.setText("");
        txtquantidade.setText("");
        txtnome.setText("");
     }
     private void limparCampos2(){
        txtvenda.setText("");
        txttotal.setText("0");
        txtrecebido.setText("");
        txtcliente.setText("");
     }
     private void inicializarbotao(){
        btactualizar.setEnabled(false);
        btnovo.setEnabled(false);
        bteliminar.setEnabled(false);
        btinserir.setEnabled(false);
        btnovofactura.setEnabled(true);
        btcancelar.setEnabled(true);
        jTable1.setEnabled(false);
        bttroco.setEnabled(false);
     }
     private void inicializarData(){
         String formatodata = null; 
         Date data = new Date();
         DateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
         formatodata = formato.format(data);
         txtdata.setText(formatodata);
    }
    private void btinserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btinserirMouseClicked
       // As variaveis de detalhe venda vao receber os dados das caixa de texto.
        try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    DetalheDados DAO = new DetalheDados();
                    if(DAO.incluirDetalhe(obj2)){
                        DAO.ActualizarStock(obj2);
                        JOptionPane.showMessageDialog(this,"Registo Salvo com sucesso!");
                        limparCampos();
                    }else{
                        JOptionPane.showMessageDialog(this,"Nao foi possivel salvar no banco!");
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        
        obj3 = new Venda();
        obj3.setCodvenda(parseInt(txtvenda.getText()));
        try {
            tabelafactura(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        int x = parseInt(txttotal.getText());
        obj3.setTotal( (obj2.getQuantidade() * obj2.getPreco()) + x );
        jTable1.setEnabled(true);
        btfinalizar.setEnabled(true);
        bttroco.setEnabled(true);
        txttotal.setText(Integer.toString(obj3.getTotal()));
    }//GEN-LAST:event_btinserirMouseClicked

    private void btnovofacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnovofacturaMouseClicked
        limparCampos2();                                                                                   
        try {                                           
            
            // TODO add your handling code here:
            obj3 = new Venda();
            obj3.setNomecliente(txtrecebido.getText());
            obj3.setDatavenda(txtdata.getText());
            VendaDados DAO = new VendaDados();
            try {
                if(DAO.incluirVenda(obj3)){
                    JOptionPane.showMessageDialog(this,"Iniciar factura!");
                }else{
                    JOptionPane.showMessageDialog(this,"Nao foi possivel salvar no banco!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //Codigo para pegar o ultimo codigo de venda
            List<Venda> lista = venda.pegarultimo(obj3);
            for(Venda c:lista){
                txtvenda.setText(String.valueOf(c.getCodvenda()));
                txtrecebido.setText(c.getNomecliente());
            }
        } catch (SQLException ex) {
        Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);            
        }
        try {
            tabelafactura(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        btinserir.setEnabled(true);
        btnovo.setEnabled(true);
        btfinalizar.setEnabled(false);
        bttroco.setEnabled(false);
        txttotal.setText("0");
        txttroco.setText("");
        obj3.setTotal(0);
    }//GEN-LAST:event_btnovofacturaMouseClicked

    private void btcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcancelarMouseClicked
        // TODO add your handling code here:
       int escolha = JOptionPane.showOptionDialog(null, " DESEJA CANCELAR OS DADOS ?", "ESCOLHER OPÇÃO", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]);

        if (escolha == 0) {
            obj2 = new DetalheVenda();
            obj2.setCodvenda(parseInt(txtvenda.getText()));
            DetalheDados DAO = new DetalheDados();
            try {
                DAO.cancelarDetalhe(obj2);
            } catch (SQLException ex) {
                Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            obj3 = new Venda();
            obj3.setCodvenda(parseInt(txtvenda.getText()));
            try {
                tabelafactura(jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            txttotal.setText("0");
            limparCampos();
        }
    }//GEN-LAST:event_btcancelarMouseClicked

    private void btnovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnovoMouseClicked
        // TODO add your handling code here:
        
        limparCampos();
    }//GEN-LAST:event_btnovoMouseClicked

    private void btfinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btfinalizarMouseClicked
        // TODO add your handling code here:
        
        try{
            if(validarCampos2()){
                if(preencherObjecto2()){
                    // Salvar no Banco
                    VendaDados DAO = new VendaDados();
                    DAO.actualizarVenda(obj3);
                    JOptionPane.showMessageDialog(this,"Factura finaizada com sucesso!");
                    btfinalizar.setEnabled(false);
                    inicializarbotao();
                    try {
                        tabelaproduto(jTable2);
                    } catch (SQLException ex) {
                        Logger.getLogger(JFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        
    }//GEN-LAST:event_btfinalizarMouseClicked

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
        // TODO add your handling code here:
            try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    DetalheDados DAO = new DetalheDados();
                    DAO.actualizarDetalhe(obj2);
                    obj2.setQuantidadeactualizada(quant - obj2.getQuantidade());
                    DAO.VoltarStock2(obj2);
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        
        obj3 = new Venda();
        obj3.setCodvenda(parseInt(txtvenda.getText()));
        try {
            tabelafactura(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        int x = parseInt(txttotal.getText());
        obj3.setTotal( x - (quant*prec) + (obj2.getQuantidade() * obj2.getPreco()));
        txttotal.setText(Integer.toString(obj3.getTotal()));
        limparCampos();
    }//GEN-LAST:event_btactualizarActionPerformed

    private void bteliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bteliminarMouseClicked
        // TODO add your handling code here:
        try{
            if(validarCampos()){
                if(preencherObjecto()){
                    // Salvar no Banco
                    DetalheDados DAO = new DetalheDados();
                    DAO.eliminarDetalhe(obj2);
                    DAO.VoltarStock(obj2);
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this,"Erro: "
                + erro.getMessage());
        }
        
        obj3 = new Venda();
        obj3.setCodvenda(parseInt(txtvenda.getText()));
        try {
            tabelafactura(jTable1);
        } catch (SQLException ex) {
            Logger.getLogger(JVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        int x = parseInt(txttotal.getText());
        obj3.setTotal( x - (obj2.getQuantidade() * obj2.getPreco()) );
        txttotal.setText(Integer.toString(obj3.getTotal()));
        limparCampos();
    }//GEN-LAST:event_bteliminarMouseClicked

    private void txtrecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecebidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecebidoActionPerformed

    private void btfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btfinalizarActionPerformed

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        // TODO add your handling code here:
        obj = new Produto();
        obj.setDescricaoproduto(txtnome.getText());
        try {
            tabelapesquisar(jTable2);
        } catch (SQLException ex) {
            Logger.getLogger(JProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtnomeKeyPressed

    private void txtrecebidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecebidoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtrecebidoKeyPressed

    private void txtrecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecebidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecebidoKeyTyped

    private void bttrocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttrocoMouseClicked
        // TODO add your handling code here:
        int x = parseInt(txttotal.getText());
        int y = parseInt(txtrecebido.getText());
        int z = y - x;
        txttroco.setText(Integer.toString(z));
    }//GEN-LAST:event_bttrocoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btactualizar;
    javax.swing.JButton btcancelar;
    javax.swing.JButton bteliminar;
    javax.swing.JButton btfinalizar;
    javax.swing.JButton btinserir;
    javax.swing.JButton btnovo;
    javax.swing.JButton btnovofactura;
    javax.swing.JButton bttroco;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable1;
    javax.swing.JTable jTable2;
    javax.swing.JTextField txtcliente;
    javax.swing.JTextField txtcodfunc;
    javax.swing.JTextField txtcodproduto;
    javax.swing.JTextField txtdata;
    javax.swing.JTextField txtnome;
    javax.swing.JTextField txtpreco;
    javax.swing.JTextField txtquantidade;
    javax.swing.JTextField txtrecebido;
    javax.swing.JTextField txttotal;
    javax.swing.JTextField txttroco;
    javax.swing.JTextField txtvenda;
    // End of variables declaration//GEN-END:variables
}
